eapache/starscope

doc/LANGUAGE_SUPPORT.md, lib/starscope/langs/ruby.rb, test/functional/starscope_test.rb
for reading of variables/constants, and for uses of symbols, respectively
they should automatically get put into cscope output as unmarked symbols,
implementing another part of #60
=> ruby: add `reads` and `sym` tables

CHANGELOG.md, bin/starscope, lib/starscope/db.rb
Upconverted DBs might not have been written if there were no other changes, and
unnecessary writing could have happened.
=> fix logic inversion in upconvert writing

lib/starscope/exportable.rb
Apparently 439e3e5261619d0a0b7569f4dfdff97e9aff7211 was not enough, just
unconditionally add a space to both hack strings.
=> cscope: fix inline functions again

CHANGELOG.md, lib/starscope/exportable.rb
Escape '/' characters in the line 'pattern' component of ctags records, since
otherwise they terminate that component when it is read as a vim search command.
=> ctags: escape '/' characters

doc/LANGUAGE_SUPPORT.md, lib/starscope/db.rb
Not queryable in line mode, I and want to use them for fragments.
=> Enforce and document no `!` at the beginning of table names

doc/LANGUAGE_SUPPORT.md, lib/starscope/db.rb, lib/starscope/langs/go.rb, lib/starscope/langs/ruby.rb, test/unit/db_test.rb, test/unit/langs/golang_test.rb, test/unit/langs/ruby_test.rb
It now takes the path and the contents directly, rather than just the file-name.
This is in preparation for handling nested fragments (like ruby-in-ERB).
=> Change the signature of `extract`

lib/starscope/db.rb, lib/starscope/fragment_extractor.rb, test/fixtures/db_old_subextractor.json, test/unit/db_test.rb, test/unit/fragment_extractor_test.rb
Add a magic `FragmentExtractor` which behaves like a language but wraps a real
language to parse fragments nested in another file.
Adjust `DB#extract_file` to use it.
Add a specially defined `FRAGMENT` table for extractors to yield when generating
fragments.
Fixes #61
=> Implement nested language blocks

CHANGELOG.md, lib/starscope/db.rb, test/fixtures/db_missing_language.json, test/unit/db_test.rb
(e.g. coffeescript) in loaded databases
=> Handle the existence of removed langs

CHANGELOG.md, lib/starscope/exportable.rb
If it does, we'll accidentally create a cscope file with two consecutive
newlines in the middle of a single 'real' source line. This is effectively a
corrupt file that only ever shows up if you search for a symbol on that line,
because cscope's parsing logic is so weird.
I had to read cscope's source to track this one down. The annoying case was in a
particular javascript file, but this probably solves a whole raft of heisenbugs
in ruby and go as well.
=> Ensure that `cscope_plaintext` never returns ''

Gemfile.lock, lib/starscope/langs/javascript.rb, starscope.gemspec, test/unit/langs/javascript_test.rb
A little more work for us, but seems to be more reliable when locating the end
of functions.
=> Use sourcemaps instead of retainLines

Gemfile.lock, starscope.gemspec
This skips the whole "spin up a sub-process for every single JS file" which was
extremely slow.
=> Try requiring `therubyracer` to speed up babel

lib/starscope/langs/ruby.rb
It does nothing to module meta-methods and is misleading.
=> Don't use `private` keyword in a module

lib/starscope/langs/javascript.rb, test/fixtures/sample_javascript.js, test/unit/langs/javascript_test.rb
Move to 3 passes, which kind of sucks (but isn't the perf bottleneck anyways,
that's still babel). Split them out into readable functions. Add a test for this
problem, and trim down some unnecessary sample javascript.
=> Fix double-parsing of JS static class methods

lib/starscope/langs/javascript.rb, test/fixtures/sample_javascript.js, test/functional/starscope_test.rb, test/unit/langs/javascript_test.rb
Handle `require` and `import` in javascript as actual module requires rather than as regular function calls or variable definitions.
=> JS requires

lib/starscope/langs/javascript.rb, test/fixtures/sample_javascript.js, test/unit/langs/javascript_test.rb
ES6 supports fat-arrow methods with no `{}` (e.g. `() => 42`) which is
annoyingly difficult to export as cscope without something to attach the "end of
method" tag to.
=> javascript: correctly handle braceless methods

starscope.gemspec
@iamcz this branch should hopefully avoid the dependency error when running with the parser pre-release version
ref: https://github.com/eapache/starscope/issues/148#issuecomment-164331435
=> Relax parser version requirement

lib/starscope/langs/javascript.rb, test/fixtures/sample_javascript.js, test/unit/langs/javascript_test.rb
Fix a crash when the parameter is not a string at all, and don't specially
recognize them when they're accessed on an object.
=> js: be pickier recognizing `require` calls

.rubocop.yml, .travis.yml, lib/starscope/db.rb, lib/starscope/exportable.rb, lib/starscope/fragment_extractor.rb, lib/starscope/langs/erb.rb, lib/starscope/langs/golang.rb, lib/starscope/langs/javascript.rb, lib/starscope/langs/ruby.rb, lib/starscope/output.rb, lib/starscope/queryable.rb, starscope.gemspec, test/unit/fragment_extractor_test.rb
- Upgrade rubocop version.
- Exclude the sample fixture from all cops unconditionally.
- Enable unused-method-argument and class-and-module-children.
Major whitespace changes here but nothing functional.
=> More rubocop changes

CHANGELOG.md, lib/starscope/exportable.rb, test/unit/exportable_test.rb
The way ctags files are structured, the paths in them always have to be relative
to the location of the tag file, not your project root. Starscope needs to
respect that when exporting ctags files to other directories via
`--export ctags,some/path/to/somewhere/else/tags`.
@kriansa
Fixes #163.
=> ctags: fix export to other directories

CHANGELOG.md, lib/starscope/langs/ruby.rb, test/fixtures/sample_ruby.rb, test/unit/exportable_test.rb
Per https://github.com/whitequark/parser/issues/283 the upstream parser gem will
blow up on these by default; suppress that diagnostic since the actual ruby
syntax is probably still well-formed and we want the tokens (we don't really
care about the contents of string literals).
Fixes #160.
=> ruby: fix parsing with invalid literal encoding

lib/starscope/langs/ruby.rb, test/fixtures/sample_ruby.rb
It parses weirdly. This might be an upstream parser issue really, but we
can handle it for now.
@Tikkoneus thanks for pointing this one out. Feel free to point out any other specific parse errors that should be fixed.
=> Fix handling of __ENCODING__ in ruby

bin/starscope, doc/USER_GUIDE.md
This PR supports configuring a `.starscope.json` on a per-directory basis. This resolves https://github.com/eapache/starscope/issues/180.
=> Look for .starscope.json in current dir before falling back to home folder.
